# Copyright (c) 2020 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/lite/config/hap_pack.gni")

_is_hi3516 = !defined(media_interface_upgrade)
_res_src = "launcher/src/main/resources"
_res_dst = "$target_out_dir/launcher_resources"

action("launcher_prepare_resources") {
  script = "//applications/sample/camera/launcher/copy_resources.py"
  _res_base = "launcher/src/main/resources/base/media"
  inputs = [
    "$_res_base/background.png",
    "$_res_base/weather.png",
  ]
  if (!_is_hi3516) {
    inputs += [ "$_res_base/background_1920x1080.png" ]
  }
  outputs = [ "$_res_dst/.stamp" ]
  args = [
    "--src",
    rebase_path(_res_src),
    "--dst",
    rebase_path(_res_dst),
  ]
  if (_is_hi3516) {
    args += [
      "--exclude",
      "base/media/background_1920x1080.png",
    ]
  }
}

shared_library("launcher") {
  sources = [
    "launcher/src/main/cpp/app_info.cpp",
    "launcher/src/main/cpp/app_manage.cpp",
    "launcher/src/main/cpp/long_press_view.cpp",
    "launcher/src/main/cpp/main_ability.cpp",
    "launcher/src/main/cpp/main_ability_slice.cpp",
    "launcher/src/main/cpp/swipe_view.cpp",
    "launcher/src/main/cpp/time_weather_view.cpp",
    "launcher/src/main/cpp/view_group_page.cpp",
  ]

  deps = [
    "${aafwk_lite_path}/frameworks/ability_lite:aafwk_abilitykit_lite",
    "${appexecfwk_lite_path}/frameworks/bundle_lite:bundle",
    "//foundation/arkui/ui_lite:ui_lite",
    "//foundation/distributeddatamgr/kv_store/interfaces/inner_api/kv_store:kv_store",
    "//foundation/graphic/graphic_utils_lite:utils_lite",
    "//foundation/graphic/surface_lite",
    "//foundation/systemabilitymgr/samgr_lite/samgr:samgr",
  ]

  include_dirs = [
    "launcher/src/main/cpp",
    "..",
    "${aafwk_lite_path}/interfaces/kits/ability_lite",
    "${appexecfwk_lite_path}/interfaces/kits/bundle_lite",
    "${aafwk_lite_path}/interfaces/kits/want_lite",
  ]

  defines = [
    "ENABLE_WINDOW=1",
    "ABILITY_WINDOW_SUPPORT",
    "OHOS_APPEXECFWK_BMS_BUNDLEMANAGER",
  ]

  if (_is_hi3516) {
    defines += [ "LAUNCHER_NO_BACKGROUND=1" ]
  }
}

hap_pack("launcher_hap") {
  deps = [
    ":launcher",
    ":launcher_prepare_resources",
  ]
  mode = "hap"
  json_path = "launcher/src/main/config.json"
  ability_so_path = "$root_out_dir/liblauncher.so"
  force = "true"
  cert_profile = "cert/com.huawei.launcher_AppProvision_release.p7b"
  resources_path = _res_dst
  hap_name = "launcher"
  privatekey = "HOS Application Provision Release"
}
